### ISSUE TITLE
[BUG] Exception: Connection closed while reading from the driver

### ISSUE THREAD

**Issue by Munchen777** [Kaliiiiiiiiii-Vinyzu/patchright#22]
### System info
- Playwright Version: ***v1.40***
- Operating System: ***macOS Sonoma 14.6***
- Browser: ***Chromium***
- Other info:

### Source code

```
     async def func():

       <here I permorm other actions (async requests and so on)>

        async with async_playwright() as p:
            args = [
                "--disable-blink-features=AutomationControlled",
            ]
            browser = await p.chromium.launch(
                channel="chrome",
                headless=False,
                proxy=self.client.proxy,
                args=args,
            )
            page = await context.new_page()
            await page.goto("https://playwright.dev/")
```
I suppose the problem with context manager. It stops in context manager thus it isn't opened a bowser window.

```
/Users/georgiy/PycharmProjects/StoryProtocol/.venv/lib/python3.11/site-packages/undetected_playwright/driver/node: Permission denied
Traceback (most recent call last):
  File "/Users/georgiy/PycharmProjects/StoryProtocol/main.py", line 102, in <module>
    asyncio.run(runner.main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/georgiy/PycharmProjects/StoryProtocol/main.py", line 95, in main
    await faucet_worker.get_tokens_from_faucet()
  File "/Users/georgiy/PycharmProjects/StoryProtocol/modules/faucet_module.py", line 244, in get_tokens_from_faucet
    async with async_playwright() as p:
  File "/Users/georgiy/PycharmProjects/StoryProtocol/.venv/lib/python3.11/site-packages/undetected_playwright/async_api/_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Connection closed while reading from the driver
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Connection.run.<locals>.init() done, defined at /Users/georgiy/PycharmProjects/StoryProtocol/.venv/lib/python3.11/site-packages/undetected_playwright/_impl/_connection.py:273> exception=Exception('Connection closed while reading from the driver')>
Traceback (most recent call last):
  File "/Users/georgiy/PycharmProjects/StoryProtocol/main.py", line 102, in <module>
    asyncio.run(runner.main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/georgiy/PycharmProjects/StoryProtocol/main.py", line 95, in main
    await faucet_worker.get_tokens_from_faucet()
  File "/Users/georgiy/PycharmProjects/StoryProtocol/modules/faucet_module.py", line 244, in get_tokens_from_faucet
    async with async_playwright() as p:
  File "/Users/georgiy/PycharmProjects/StoryProtocol/.venv/lib/python3.11/site-packages/undetected_playwright/async_api/_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Connection closed while reading from the driver
```

**My steps:**

```
pip install undetected-playwright-patch
```

```
chmod +x <path> (path I take from console where I saw an exception. Further it isn't appeared)
```

Further try to run code

**Comment by KrAsH-CoD3** [comment]
> ### Source code
> ```
>      async def func():
> 
>        <here I permorm other actions (async requests and so on)>
> 
>         async with async_playwright() as p:
>             args = [
>                 "--disable-blink-features=AutomationControlled",
>             ]
>             browser = await p.chromium.launch(
>                 channel="chrome",
>                 headless=False,
>                 proxy=self.client.proxy,
>                 args=args,
>             )
>             page = await context.new_page()
>             await page.goto("https://playwright.dev/")
> ```

Not sure if it probably a typo, the `launch` method returns a BrowserType. On the following line, you are using `context`. Is this a typo?
