### ISSUE TITLE
[BUG] AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

### ISSUE THREAD

**Issue by TimAidley** [Kaliiiiiiiiii-Vinyzu/patchright#26]
### System info
- Playwright Version: 1.40.0.post1700587210000
- Operating System: Linux Mint 24
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

This is the example code given in the documentation:

```
# undetected-playwright here!
from undetected_playwright.sync_api import sync_playwright

with sync_playwright() as p:
    args = []

    # disable navigator.webdriver:true flag
    args.append("--disable-blink-features=AutomationControlled")
    browser = p.chromium.launch(args=args, headless=False)
    page = browser.new_page()
    page.goto("https://nowsecure.nl/#relax")
    input("Press ENTER to continue to Creep-JS:")
    page.goto("https://nowsecure.nl/#relax")
    page.goto("https://abrahamjuliot.github.io/creepjs/")
    input("Press ENTER to exit:")
    browser.close()
```

I found the same thing happen with my own code.

**Steps**
- [Run the test]

**Expected**

It should attempt to open a browser

**Actual**

```
/home/tim/src/PwTest/.venv/bin/python /home/tim/src/PwTest/pwexample.py 
/home/tim/src/PwTest/.venv/lib/python3.12/site-packages/undetected_playwright/driver/playwright.sh: 6: /home/tim/src/PwTest/.venv/lib/python3.12/site-packages/undetected_playwright/driver/node: Permission denied
Traceback (most recent call last):
  File "/home/tim/src/PwTest/pwexample.py", line 4, in <module>
    with sync_playwright() as p:
  File "/home/tim/src/PwTest/.venv/lib/python3.12/site-packages/undetected_playwright/sync_api/_context_manager.py", line 79, in __enter__
    playwright = self._playwright
                 ^^^^^^^^^^^^^^^^
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at /home/tim/src/PwTest/.venv/lib/python3.12/site-packages/undetected_playwright/_impl/_connection.py:274> wait_for=<Future finished result=None> cb=[ProtocolCallback.__init__.<locals>.cb() at /home/tim/src/PwTest/.venv/lib/python3.12/site-packages/undetected_playwright/_impl/_connection.py:195]>
Future exception was never retrieved
future: <Future finished exception=Exception('Connection closed while reading from the driver')>
Exception: Connection closed while reading from the driver

Process finished with exit code 1
```

**Comment by Vinyzu** [comment]
Should be Solved with Update to Patchright.
If not, reopen this issue.
